# -*- coding: utf-8 -*-
"""TASK1_CODSOFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4_vcD2Zdr7mTQYvLrWgLdYCKoODV3pj

# ***Task-1: TITANIC SURVIVAL PREDICTION***


*   Author: Vinay Santosh Kulkarni
*   Batch : Augest
*   Domain: Data Science
*   Aim to bulid a model that predicts whether a passenger on the Titanic survived or not

***IMPORTING IMPORTANT LIBRARIES***
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""***IMPORTING DATASET***"""

df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head(10)

df.shape

df.describe()

"""**From above cell it is clear there are few missing values in age column**"""

df['Survived'].value_counts()

#lets visualize the count of survivals wrt pclass
sns.countplot(x=df['Survived'], hue=df['Pclass'])

df['Sex']

#lets visualize the count of survivals wrt Gender
sns.countplot(x = df["Sex"], hue = df['Survived'] )

#look at survival rate by sex
df.groupby('Sex')[['Survived']].mean()

df['Sex'].unique()

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df["Sex"] = labelencoder.fit_transform(df["Sex"])
df.head()

df["Sex"], df["Survived"]

sns.countplot(x = df["Sex"], hue = df['Survived'])

df.isna().sum()

# After dropping non required coloumb
df = df.drop(["Age"], axis = 1)

df_final = df
df_final.head(10)

"""***MODEL TRAINING***


"""

x = df[["Pclass", "Sex"]]
y = df["Survived"]

from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

from sklearn.linear_model import LogisticRegression

log = LogisticRegression(random_state=0)
log.fit(X_train, Y_train)

"""***MODEL PREDICTION***"""

pred = print(log.predict(X_test))

print(Y_test)

import warnings
warnings.filterwarnings("ignore")
res = log.predict([[2,1]])
if(res)==0:
  print("So sorry! Not survived")
else:
  print("Survived")